# Generated by Django 3.0.1 on 2019-12-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20191229_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
